//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolX.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default 
        {
            get 
            {
                return defaultInstance;
            }
        }

        #region Menustrip

        #region MenuStripGradientBegin
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MenuStripGradientBegin
        {
            get { return ((global::System.Drawing.Color)(this["MenuStripGradientBegin"])); }
            set { this["MenuStripGradientBegin"] = value; }
        }
        #endregion

        #region MenuStripGradientEnd
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DimGray")]
        public global::System.Drawing.Color MenuStripGradientEnd
        {
            get{ return ((global::System.Drawing.Color)(this["MenuStripGradientEnd"]));}
            set{ this["MenuStripGradientEnd"] = value; }
        }
        #endregion 

        #region MenuStripForeColor
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color MenuStripForeColor
        {
            get{ return ((global::System.Drawing.Color)(this["MenuStripForeColor"]));}
            set{ this["MenuStripForeColor"] = value; }
        }
        #endregion

        #region MenuItemPressedGradientBegin
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color MenuItemPressedGradientBegin
        {
            get{ return ((global::System.Drawing.Color)(this["MenuItemPressedGradientBegin"]));}
            set{ this["MenuItemPressedGradientBegin"] = value;}
        }
        #endregion

        #region MenuItemPressedGradientMiddle
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color MenuItemPressedGradientMiddle
        {
            get{ return ((global::System.Drawing.Color)(this["MenuItemPressedGradientMiddle"]));}
            set{ this["MenuItemPressedGradientMiddle"] = value;}
        }
        #endregion

        #region MenuItemPressedGradientEnd
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color MenuItemPressedGradientEnd
        {
            get{ return ((global::System.Drawing.Color)(this["MenuItemPressedGradientEnd"]));}
            set{ this["MenuItemPressedGradientEnd"] = value;}
        }
        #endregion

        #region MenuItemSelectedGradientBegin
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MenuItemSelectedGradientBegin
        {
            get{ return ((global::System.Drawing.Color)(this["MenuItemSelectedGradientBegin"]));}
            set{ this["MenuItemSelectedGradientBegin"] = value;}
        }
        #endregion

        #region MenuItemSelectedGradientEnd
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MenuItemSelectedGradientEnd
        {
            get{ return ((global::System.Drawing.Color)(this["MenuItemSelectedGradientEnd"]));}
            set{ this["MenuItemSelectedGradientEnd"] = value;}
        }
        #endregion

        #region MenuItemSelected
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MenuItemSelected
        {
            get { return ((global::System.Drawing.Color)(this["MenuItemSelected"]));}
            set { this["MenuItemSelected"] = value;}
        }
        #endregion

        #region ImageMarginGradientBegin
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color ImageMarginGradientBegin
        {
            get { return ((global::System.Drawing.Color)(this["ImageMarginGradientBegin"])); }
            set { this["ImageMarginGradientBegin"] = value; }
        }
        #endregion

        #region ImageMarginGradientMiddle
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color ImageMarginGradientMiddle
        {
            get { return ((global::System.Drawing.Color)(this["ImageMarginGradientMiddle"])); }
            set { this["ImageMarginGradientMiddle"] = value; }
        }
        #endregion

        #region ImageMarginGradientEnd
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color ImageMarginGradientEnd
        {
            get { return ((global::System.Drawing.Color)(this["ImageMarginGradientEnd"])); }
            set { this["ImageMarginGradientEnd"] = value; }
        }
        #endregion

        #region MenuBorder
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MenuBorder
        {
            get { return ((global::System.Drawing.Color)(this["MenuBorder"])); }
            set { this["MenuBorder"] = value; }
        }
        #endregion

        #region MenuItemBorder
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MenuItemBorder
        {
            get{ return ((global::System.Drawing.Color)(this["MenuItemBorder"]));}
            set{ this["MenuItemBorder"] = value;}
        }
        #endregion

        #endregion

        #region ToolStrip

        #region ToolStripForeColor
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ToolStripForeColor
        {
            get { return ((global::System.Drawing.Color)(this["ToolStripForeColor"])); }
            set { this["ToolStripForeColor"] = value; }
        }
        #endregion

        #region ToolStripBorder
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ToolStripBorder
        {
            get{ return ((global::System.Drawing.Color)(this["ToolStripBorder"]));}
            set{ this["ToolStripBorder"] = value;}
        }
        #endregion

        #region ToolStripContentPanelGradientBegin
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color ToolStripContentPanelGradientBegin
        {
            get{ return ((global::System.Drawing.Color)(this["ToolStripContentPanelGradientBegin"]));}
            set{ this["ToolStripContentPanelGradientBegin"] = value;}
        }
        #endregion

        #region ToolStripContentPanelGradientEnd
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color ToolStripContentPanelGradientEnd
        {
            get { return ((global::System.Drawing.Color)(this["ToolStripContentPanelGradientEnd"])); }
            set { this["ToolStripContentPanelGradientEnd"] = value; }
        }
        #endregion

        #region ToolStripDropDownBackground
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color ToolStripDropDownBackground
        {
            get { return ((global::System.Drawing.Color)(this["ToolStripDropDownBackground"])); }
            set { this["ToolStripDropDownBackground"] = value; }
        }
        #endregion

        #region ToolStripGradientBegin
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color ToolStripGradientBegin
        {
            get { return ((global::System.Drawing.Color)(this["ToolStripGradientBegin"])); }
            set { this["ToolStripGradientBegin"] = value; }
        }
        #endregion

        #region ToolStripGradientMiddle
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color ToolStripGradientMiddle
        {
            get { return ((global::System.Drawing.Color)(this["ToolStripGradientMiddle"])); }
            set { this["ToolStripGradientMiddle"] = value; }
        }
        #endregion

        #region ToolStripGradientEnd
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ToolStripGradientEnd
        {
            get{ return ((global::System.Drawing.Color)(this["ToolStripGradientEnd"]));}
            set{ this["ToolStripGradientEnd"] = value;}
        }
        #endregion

        #endregion

        #region StatusStrip

        #region StatusStripGradientBegin
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color StatusStripGradientBegin
        {
            get{ return ((global::System.Drawing.Color)(this["StatusStripGradientBegin"]));}
            set{ this["StatusStripGradientBegin"] = value;}
        }
        #endregion

        #region StatusStripGradientEnd
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DimGray")]
        public global::System.Drawing.Color StatusStripGradientEnd
        {
            get{ return ((global::System.Drawing.Color)(this["StatusStripGradientEnd"]));}
            set{ this["StatusStripGradientEnd"] = value;}
        }
        #endregion

        #region StatusStripForeColor
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color StatusStripForeColor
        {
            get{ return ((global::System.Drawing.Color)(this["StatusStripForeColor"]));}
            set{ this["StatusStripForeColor"] = value;}
        }
        #endregion

        #endregion
    }
}
